version: "3.8"

services:
  web:
    depends_on: 
      - api

    build: ./frontend
    ports:
      - 5173:5173

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  api: 
    build: ./backend
    
    ports: 
      - 5000:5000
    env_file:
      - ./backend/.env

    
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        
        - path: ./backend
          target: /app
          action: sync

    volumes:
      - mern:/data/db
volumes:
  mern: