apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
  labels:
    app: todo-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: todo-web
          image: shayaliza/todo:web
