apiVersion: v1
kind: Service
metadata:
  name: alizak8s
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 5173
  selector:
    app: todo-web #same should be in deployemnt file
  type: LoadBalancer
# to run this file
# kubectl apply -f serviceKube.yaml
# minikube service todo-web
