version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm start


# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "5000:5000"
#     environment:
#       - NODE_ENV=production
#       - MONGO_URI=mongodb+srv://<username>:<password>@<cluster>.mongodb.net/<dbname>?retryWrites=true&w=majority
#     volumes:
#       - .:/app
#     command: npm start